# Generated by Django 5.0.6 on 2024-05-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrovanikorisnik',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.korisnik')),
                ('ime', models.CharField(db_column='Ime', max_length=20)),
                ('prezime', models.CharField(db_column='Prezime', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('brojtelefona', models.CharField(db_column='BrojTelefona', max_length=20)),
                ('datumrodjenja', models.DateTimeField(db_column='DatumRodjenja')),
                ('mestorodjenja', models.CharField(db_column='MestoRodjenja', max_length=20)),
                ('brojkartice', models.DecimalField(db_column='BrojKartice', decimal_places=0, max_digits=10)),
                ('slika', models.TextField(db_column='Slika')),
            ],
            options={
                'db_table': 'registrovanikorisnik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kreator',
            fields=[
                ('idkor', models.IntegerField(db_column='IdKor', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kreator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('idkor', models.IntegerField(db_column='IdKor', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kupac',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kolekcionar',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='profiles.registrovanikorisnik')),
            ],
            options={
                'db_table': 'kolekcionar',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='kreator',
            name='idkor',
            field=models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING,
                                       primary_key=True, serialize=False, to='profiles.registrovanikorisnik'),
        ),
        migrations.AlterField(
            model_name='kupac',
            name='idkor',
            field=models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING,
                                       primary_key=True, serialize=False, to='profiles.registrovanikorisnik'),
        ),
    ]
