# Generated by Django 4.2.13 on 2024-05-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovanikorisnik',
            name='kupljenihNFT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrovanikorisnik',
            name='prodatihNFT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrovanikorisnik',
            name='slika',
            field=models.ImageField(db_column='Slika', upload_to='profile_images/'),
        ),
    ]
