# Generated by Django 4.2.13 on 2024-05-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_registrovanikorisnik_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovanikorisnik',
            name='datumkreiranja',
            field=models.DateField(blank=True, db_column='DatumKreiranja', null=True),
        ),
    ]
