# Generated by Django 5.0.6 on 2024-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_kolekcionar_idkor_alter_kreator_idkor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovanikorisnik',
            name='datumkreiranja',
            field=models.DateField(db_column='DatumKreiranja', null=True),
        ),
        migrations.AlterField(
            model_name='registrovanikorisnik',
            name='kupljenihNFT',
            field=models.IntegerField(db_column='kupljenihNft', default=0),
        ),
        migrations.AlterField(
            model_name='registrovanikorisnik',
            name='prodatihNFT',
            field=models.IntegerField(db_column='prodatihNft', default=0),
        ),
    ]
