# Generated by Django 5.0.6 on 2024-05-14 13:58

import django.db.models.deletion
from django.db import migrations, models

from profiles.models import Registrovanikorisnik


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Listanft',
            fields=[
                ('idlis', models.AutoField(db_column='IdLis', primary_key=True, serialize=False)),
                ('ukupnavrednost', models.FloatField(db_column='UkupnaVrednost')),
                ('brojnft', models.IntegerField(db_column='BrojNFT')),
                ('idvla',
                 models.ForeignKey('profiles.Registrovanikorisnik', on_delete=models.DO_NOTHING, db_column='IdVla',
                                   null=True)),
            ],
            options={
                'db_table': 'listanft',
                'managed': True,
            },
        ),




        migrations.CreateModel(
            name='Izlozba',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.listanft')),
                ('naziv', models.CharField(blank=True, db_column='Naziv', max_length=18, null=True)),
                ('datumkreiranja', models.CharField(blank=True, db_column='DatumKreiranja', max_length=18, null=True)),
                ('prosecnaocena', models.CharField(blank=True, db_column='ProsecnaOcena', max_length=18, null=True)),
            ],
            options={
                'db_table': 'izlozba',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kolekcija',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.listanft')),
            ],
            options={
                'db_table': 'kolekcija',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.listanft')),
            ],
            options={
                'db_table': 'portfolio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pripada',
            fields=[
                ( 'idpri',models.AutoField(db_column='IdPri', primary_key=True, serialize=False)),

                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING,  serialize=False, to='exhibitions.listanft')),

                ('idnft', models.OneToOneField(db_column='IdNFT', on_delete=django.db.models.deletion.DO_NOTHING, to='nft.nft')),
],
            options={
                'db_table': 'pripada',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='pripada',
            name='idlis',
            field=models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING,
                                       to='exhibitions.listanft'),
        )

    ]
