# Generated by Django 5.0.6 on 2024-05-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_alter_izlozba_idlis_alter_kolekcija_idlis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='izlozba',
            name='opis',
            field=models.CharField(blank=True, db_column='Opis', max_length=18, null=True),
        ),
    ]
