# Generated by Django 5.0.6 on 2024-05-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_izlozba_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izlozba',
            name='opis',
            field=models.CharField(blank=True, db_column='Opis', max_length=128, null=True),
        ),
    ]
