# Generated by Django 4.2.13 on 2024-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnik',
            options={},
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='korime',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='sifra',
        ),
        migrations.AddField(
            model_name='korisnik',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='password',
            field=models.CharField(default=' ', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='korisnik',
            name='user_type',
            field=models.CharField(default='guest', max_length=20),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='username',
            field=models.CharField(default=' ', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='idkor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='korisnik',
            table=None,
        ),
    ]
