# Generated by Django 4.2.13 on 2024-05-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_alter_kolekcionar_idkor_alter_kreator_idkor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('idnft', models.AutoField(db_column='IdNFT', primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='Naziv', max_length=20)),
                ('vrednost', models.FloatField(db_column='Vrednost')),
                ('prosecnaocena', models.DecimalField(db_column='ProsecnaOcena', decimal_places=0, max_digits=10)),
                ('opis', models.CharField(db_column='Opis', max_length=256)),
                ('slika', models.ImageField(db_column='Slika', upload_to='nft_images/')),
                ('url', models.CharField(db_column='Url', max_length=128)),
                ('idkre', models.ForeignKey(blank=True, db_column='IdKre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.registrovanikorisnik')),
                ('idvla', models.ForeignKey(blank=True, db_column='IdVla', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nft_idvla_set', to='profiles.registrovanikorisnik')),
            ],
            options={
                'db_table': 'nft',
                'managed': True,
            },
        ),
    ]
