# Generated by Django 5.0.6 on 2024-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='nft',
        #    name='url',
        #    field=models.CharField(db_column='Url', default='', max_length=128),
        #    preserve_default=False,
        #),
        migrations.AlterField(
            model_name='nft',
            name='opis',
            field=models.CharField(db_column='Opis', max_length=256),
        ),
        migrations.AlterField(
            model_name='nft',
            name='slika',
            field=models.ImageField(db_column='Slika', upload_to='nft_images/'),
        ),
    ]
