# Generated by Django 5.0.6 on 2024-05-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_nft_url_alter_nft_opis_alter_nft_slika'),
        ('profiles', '0007_alter_registrovanikorisnik_datumkreiranja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('idoce', models.AutoField(db_column='IdOce', default=None, primary_key=True, serialize=False)),
                ('ocena', models.IntegerField(db_column='Ocena')),
                ('idkor', models.OneToOneField(db_column='IdKor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.registrovanikorisnik')),
                ('idnft', models.OneToOneField(db_column='IdNFT', on_delete=django.db.models.deletion.CASCADE, to='nft.nft')),
            ],
            options={
                'db_table': 'ocena',
                'managed': True,
            },
        ),
    ]
