# Generated by Django 5.0.6 on 2024-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='prosecnaocena',
            field=models.DecimalField(db_column='ProsecnaOcena', decimal_places=0, max_digits=10, null=True),
        ),
    ]
